version: "3"

services:
  web:
    build: .
    command: bash -c "python entrypoint.py && uwsgi --ini ../configs/uwsgi.ini"
    volumes:
      - /var/www/${COMPOSE_PROJECT_NAME}:/app/data
    depends_on:
      - db
    restart: on-failure
    env_file: .env

  db:
    image: postgres:latest
    restart: on-failure
    volumes:
      - ict_hack_db:/var/lib/postgresql
    env_file: .env

volumes:
  ict_hack_db:
    external: true
