# Generated by Django 3.2.10 on 2021-12-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievement_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
    ]
