# Generated by Django 3.2.10 on 2021-12-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='pgas_converted',
            field=models.BooleanField(default=False, verbose_name='Начислены баллы ПГАС'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='pgas_converted',
            field=models.BooleanField(default=False, verbose_name='Начислены баллы ПГАС'),
        ),
    ]
