# Generated by Django 3.2.10 on 2021-12-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_remove_pgas_converted_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='pgas_converted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начислены баллы ПГАС (дата)'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='pgas_converted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начислены баллы ПГАС (дата)'),
        ),
    ]
