# Generated by Django 3.2.10 on 2021-12-19 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.PositiveSmallIntegerField(choices=[(1, 'Учеба - 5'), (2, 'Учеба - 10'), (3, 'Учеба - 5'), (4, 'Учеба - 10'), (5, 'Учеба - 5'), (6, 'Учеба - 10'), (7, 'Учеба - 5'), (8, 'Учеба - 10'), (9, 'Учеба - 5'), (10, 'Учеба - 10'), (11, 'Топ-3 в рейтинге')], verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Учебная деятельность'), (2, 'Научно-исследовательская деятельность'), (3, 'Общественная деятельность'), (4, 'Культурно-творческая деятельность'), (5, 'Спортивная деятельность')], null=True, verbose_name='Категория')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trophies_trophy_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.PROTECT, on_update=True, related_name='trophies_trophy_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлён')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTrophy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('code', models.PositiveSmallIntegerField(choices=[(1, 'Учеба - 5'), (2, 'Учеба - 10'), (3, 'Учеба - 5'), (4, 'Учеба - 10'), (5, 'Учеба - 5'), (6, 'Учеба - 10'), (7, 'Учеба - 5'), (8, 'Учеба - 10'), (9, 'Учеба - 5'), (10, 'Учеба - 10'), (11, 'Топ-3 в рейтинге')], verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Учебная деятельность'), (2, 'Научно-исследовательская деятельность'), (3, 'Общественная деятельность'), (4, 'Культурно-творческая деятельность'), (5, 'Спортивная деятельность')], null=True, verbose_name='Категория')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлён')),
            ],
            options={
                'verbose_name': 'История изменений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
