# Generated by Django 3.2.10 on 2021-12-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name': 'Трофей', 'verbose_name_plural': 'Трофеи'},
        ),
    ]
