# Generated by Django 3.2.10 on 2021-12-19 05:53

from django.db import migrations, models
import trophies.models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0003_alter_trophy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrophy',
            name='icon',
            field=models.TextField(default='', max_length=100, verbose_name='Иконка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trophy',
            name='icon',
            field=models.FileField(default='', upload_to=trophies.models.trophy_icon_upload, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
