# Generated by Django 3.2.10 on 2021-12-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0004_add_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrophy',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Учеба - 5'), (2, 'Учеба - 10'), (3, 'Наука - 5'), (4, 'Наука - 10'), (5, 'Активность - 5'), (6, 'Активность - 10'), (7, 'Культура - 5'), (8, 'Культура - 10'), (9, 'Спорт - 5'), (10, 'Спорт - 10'), (11, 'Топ-3 в рейтинге')], verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Учеба - 5'), (2, 'Учеба - 10'), (3, 'Наука - 5'), (4, 'Наука - 10'), (5, 'Активность - 5'), (6, 'Активность - 10'), (7, 'Культура - 5'), (8, 'Культура - 10'), (9, 'Спорт - 5'), (10, 'Спорт - 10'), (11, 'Топ-3 в рейтинге')], verbose_name='Код'),
        ),
    ]
