# Generated by Django 3.2.10 on 2021-12-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на аватар'),
        ),
    ]
