name: Deploy to server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PASSWORD: ${{ secrets.SSH_PASSWORD }}
        script: cd ~/ict-hack-backend/ && git pull && make run
