# Generated by Django 3.2.10 on 2021-12-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
