# Generated by Django 3.2.10 on 2021-12-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'На рассмотрении'), (2, 'Мероприятие одобрено'), (3, 'Мероприятие отклонено'), (4, 'Ожидается отправка отчёта'), (5, 'Ожидается утверждение отчёта'), (6, 'Отчёт утверждён'), (7, 'Отчёт отлконён')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'На рассмотрении'), (2, 'Мероприятие одобрено'), (3, 'Мероприятие отклонено'), (4, 'Ожидается отправка отчёта'), (5, 'Ожидается утверждение отчёта'), (6, 'Отчёт утверждён'), (7, 'Отчёт отлконён')], default=1, verbose_name='Статус'),
        ),
    ]
