# Generated by Django 3.2.10 on 2021-12-19 00:36

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=events.models.event_report_upload, verbose_name='Отчёт'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='report',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Отчёт'),
        ),
    ]
