# Generated by Django 3.2.10 on 2021-12-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('events', '0007_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachments.image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attachments.image', verbose_name='Изображение'),
        ),
    ]
